### ISSUE TITLE
troddit cannot display this nsfw content. use reddxxx instead.

### ISSUE THREAD

**Issue by Vozf** [burhan-syed/troddit#121]
What has happened? Troddit always worked with nsfw and now it redirects to some unknown 3rd party site I don't want to use. how to revert the changes?

**Comment by burhan-syed** [comment]
You can self host to use as before otherwise troddit. com will not be displaying this content.

**Comment by Vozf** [comment]
Why?

**Comment by burhan-syed** [comment]
There are significant legal stipulations in hosting sites with this kind of content which I am not interested in and it has become an increasing issue as troddit has gained popularity. The troddit.com domain remains completely free to use and is not a business nor a source of revenue as there are zero ads or income streams outside of a donations. 
For now, troddit.com remains more so as a demo for this repository. Others have take it upon themselves to host domains (such Reddxxx) without these restrictions and troddit itself remains open source and capable of self hosting without any kind of restrictions.

**Comment by IskenderWang** [comment]
> There are significant legal stipulations in hosting sites with this kind of content which I am not interested in and it has become an increasing issue as troddit has gained popularity. The troddit.com domain remains completely free to use and is not a business nor a source of revenue as there are zero ads or income streams outside of a donations. For now, troddit.com remains more so as a demo for this repository. Others have take it upon themselves to host domains (such Reddxxx) without these restrictions and troddit itself remains open source and capable of self hosting without any kind of restrictions.

@burhan-syed While this is understandable, it seems somewhat unclear who these "others" are and if you know them personally, or are in some way affiliated with them or endorse the use of their site. There's nothing wrong with any of that as far as I know; however, there is a HUGE issue if these individuals over at Reddxxx (most I could gather about the author is u/youhat33 on reddit) — while they have given your work credit on their about page and do describe their site as a "fork" of it — have created a derivative work/fork of troddit but have NOT made the source code for it available anywhere (that I, or anyone else could find, at least). It's not provided anywhere on the site itself, it's not on GitHub, and looking around a bit I still couldn't find any repository which hosts the codebase for the site. It looks like no one has pressed them on/asked them about this matter so far either.

I'm sure you're aware that this situation, assuming reddxxx really is closed-source, would be a blatant violation of the license terms, since you yourself have chosen the AGPL license. That has to be the biggest legal stipulation here, if I'm not mistaken. I don't know if you're in contact with those people, nor can I know if this was just an honest oversight or if there was some actual hope that no one would see an issue with this situation, but hopefully it gets sorted out :)

**Comment by burhan-syed** [comment]
@IskenderWang thanks for your concern. I'm not going to go into too much detail but Reddxxx is operating under a separate proprietary license for this project.

**Comment by YaBoiMax** [comment]
This is a bit of a problem since some posts on normal subreddits are marked as nsfw even though they are not pornographic, one example would be some posts on r/shitposting are marked as nsfw
