### ISSUE TITLE
Troddit keeps refreshing and loosing my place no matter what settings I use.

### ISSUE THREAD

**Issue by mattmarcum** [burhan-syed/troddit#137]
I've got everything I can think of set to keep troddit from refreshing, but it still does.  So annoying.  I'm a first time user and like it, but I can't use it if it just keeps automatically refreshing right while I'm reading something.

![Screenshot from 2022-12-13 23-21-55](https://user-images.githubusercontent.com/4745044/207513013-6483eb8e-7879-4057-8ce3-36269df3c812.png)

**Comment by burhan-syed** [comment]
Try enabling 'Ask to Update'.
Currently if you navigate from one feed back to another troddit will check for new posts in the background while displaying the previously cached posts. 
Because 'Ask to Update' is toggled off any new posts will be automatically inserted into the feed and any cached post you were reading may be shifted down causing you to lose your place.
