### ISSUE TITLE
Markdown escaping issue

### ISSUE THREAD

**Issue by grandeljay** [burhan-syed/troddit#41]
When I post in troddit with markdown, something like:

<pre>
Hello `world`
</pre>

It ends up really borked in reddit:
<pre>
Hello \`world\`
</pre>

And the formatting looks really messed up for me then. I'm guessing troddit is escaping the input but reddit isn't removing the slashes? Maybe not escaping would solve the issue?

**Comment by grandeljay** [comment]
Generally I would like to add that Markdown does not seem to render well in troddit. I often have to open the original reddit link to see the markdown

**Comment by burhan-syed** [comment]
This comes down to Reddit having its own flavor of markdown which the previous WYSIWYG editor on troddit did not always properly covert over. 
If someone is able to suggest or contribute a PR to convert from draft to Reddit's markdown that would be great. 
Otherwise for now I've changed to a simple textarea. Typing markdown in this area will render the markdown when submitted to Reddit.

**Comment by burhan-syed** [comment]
The original issue was resolved with the change to the plaintext editor so I'm closing this. 
Introducing a WYSIYWG or 'fancy pants' editor that works well with Reddit markdown will be an enhancement for the future.
