### ISSUE TITLE
Feature request - To be able to change the default port in docker

### ISSUE THREAD

**Issue by imTHAI** [burhan-syed/troddit#50]
Hello,

Could you give the possibility to change the default port with the docker image ? (useful when using host network)

Rmq: I'm almost sure I already opened this request here, but I can't find it anymore, even in the closed ones.

Thank you,
KR,

**Comment by burhan-syed** [comment]
There's now an option to provide an arg (portnum) to change the default port when the docker image is built. To do this you'll need to build the image yourself. If there's a way to do this with the hosted docker image let me know. Otherwise I'm closing this.

92ace5eb6b1f82df015f66bd88aea6f0e41820da

**Comment by imTHAI** [comment]
Hello,
Ok I don’t know why I didn’t get the info last time. I confirm it works with this commit. 
KR,
