### ISSUE TITLE
[Suggestion] Use Masonic (virtual scrolling) in comments section

### ISSUE THREAD

**Issue by SamyzKhalil** [burhan-syed/troddit#62]
For better performance on low-end devices.

**Comment by burhan-syed** [comment]
Masonic and other virtualization libraries (namely react-virtual) did not meaningfully improve comment scrolling. They instead proved to decrease frames especially on low end devices presumably due to the added overhead and because of the relatively low number of rendered elements for comments compared to posts on the feed. 

I also experimented with hiding child comments and elements in children when not in view but using intersection observers and rendering components while scrolling proved a worse experience than leaving it as is. 

Instead, I've made other optimizations for small devices like hiding vote button SVGs. Further improvement can be made by disable features such as user icons, gilding icons, and user flairs but I've left these on by default and toggle-able in the settings. 

I may revisit this when react-virtual matures some more as it was promising but handling resize events was not fast enough to replace my current implementation.
